export const ROOMS = ["Hội trường 1", "Hội trường 2", "Hội trường 3", "Hội trường 4", "Hội trường 5", "Hội trường 6", "Hội trường 7", "Hội trường 8", "Hội trường 9", "Hội trường 10"];
export const SHIFTS = ["Sáng", "Chiều", "Cả ngày"];
export const WEEKDAYS = ["T2", "T3", "T4", "T5", "T6", "T7", "CN"];
export const MONTHS = ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"];
export const JUROR = [
    "Lê Thị Tú Anh",
    "Ngụy Mộng Cầm",
    "Nguyễn Tùng Châu",
    "Nguyễn Thị Lệ Hoa",
    "Lê Minh Hoàng",
    "Nguyễn Thị Kim Hường",
    "Trần Thị Minh Hường",
    "Trần Thị Đức Nghiêm",
    "Võ Thị Bích Ngọc",
    "Võ Thị Mỹ Ngọc",
    "Lê Thị Kiều Oanh",
    "Nguyễn Thị Lan Phương",
    "Nguyễn Tấn Tài",
    "Châu Thanh Tân",
    "Nguyễn Thị Thanh Thảo",
    "Đặng Ngọc Thu",
    "Huỳnh Thị Thu Vân",
    "Quách Tử Điệc",
    "Trần Thanh Khen",
    "Huỳnh Anh Dũng",
    "Hồ Minh Hùng",
    "Quách Thái Vạn Thuận",
    "Huỳnh Kim Phượng",
    "Trần Văn Thanh",
    "Võ Hữu Phước",
    "Nguyễn Thanh Phúc",
    "Phạm Công Toàn",
    "Trần Trung Nghĩa",
    "Trần Thị Tuyết Nga",
    "Nguyễn Thị Út",
    "Trương Hữu Phước",
    "Trần Thanh Hùng",
    "Lê Thị Hồng Vân",
    "Phạm Hữu Hiệp",
    "Trần Mỹ Huyền",
    "Nguyễn Thị Ngọc Tuyết",
    "Nguyễn Quế Hào",
    "Nguyễn Thị Hồng Phương",
    "Lê Minh Mẫn",
    "Nguyễn Trọng Trí",
    "Mai Văn Trí",
    "Nguyễn Minh Trí",
    "Nguyễn Thành Tài",
    "Nguyễn Thị Diệu Phước",
    "Lê Anh Vũ",
    "Huỳnh Hữu Phi"
];
export const YEARS = Array.from({ length: 11 }, (_, i) => 2020 + i);
