export const ROOMS = ["Hội trường 1", "Hội trường 2", "Hội trường 3", "Hội trường 4", "Hội trường 5", "Hội trường 6", "Hội trường 7", "Hội trường 8", "Hội trường 9", "Hội trường 10"];
export const SHIFTS = ["Sáng", "Chiều", "Cả ngày"];
export const WEEKDAYS = ["T2", "T3", "T4", "T5", "T6", "T7", "CN"];
export const MONTHS = ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"];
export const JUROR = [
    "Lê Thị Tú Anh",
    "Ngụy Mộng Cầm",
    "Nguyễn Tùng Châu",
    "Huỳnh Thị Chi",
    "Nguyễn Văn Cường",
    "Trần Quang Đông",
    "Nguyễn Thị Lệ Hoa",
    "Lê Minh Hoàng",
    "Nguyễn Văn Hoàng",
    "Đoàn Văn Huệ",
    "Nguyễn Thị Kim Hường",
    "Trần Thị Minh Hường",
    "Trần Thị Đức Nghiêm",
    "Võ Thị Bích Ngọc",
    "Võ Thị Mỹ Ngọc",
    "Lê Thị Kiều Oanh",
    "Trần Văn Mỹ Phúc",
    "Dương Thị Phụng",
    "Nguyễn Thị Lan Phương",
    "Nguyễn Tấn Tài",
    "Châu Thanh Tân",
    "Nguyễn Thị Thanh Thảo",
    "Lê Văn Thới",
    "Đặng Ngọc Thu",
    "Huỳnh Đặng Anh Thư",
    "Phạm Văn Tư",
    "Huỳnh Thị Thu Vân",
    "Nguyễn Phương Thanh",
    "Quách Tử Điệc",
    "Nguyễn Văn Phước",
    "Nguyễn Văn Trước",
    "Trần Thanh Khen",
    "Huỳnh Anh Dũng",
    "Hồ Minh Hùng",
    "Lê Minh Toàn",
    "Trần Thanh Hiếu",
    "Nguyễn Thị Hương",
    "Quách Thái Vạn Thuận",
    "Trần Văn Kiệt",
    "Huỳnh Kim Phượng",
    "Võ Thế Khoa",
    "Nguyễn Văn Nghĩa",
    "Trần Văn Thanh",
    "Võ Hữu Phước",
    "Nguyễn Thanh Phúc",
    "Nguyễn Thị Tuyết Trang",
    "Phạm Công Toàn",
    "Trần Bích Trang",
    "Trần Trung Nghĩa",
    "Nguyễn Thị Hằng",
    "Trần Thị Tuyết Nga",
    "Nguyễn Thị Út",
    "Trương Hữu Phước",

    // New
    "Trần Thanh Hùng",
    "Lê Thị Hồng Vân",
    "Phạm Hữu Hiệp",
    "Trần Mỹ Huyền",
    "Nguyễn Thị Ngọc Tuyết",
    "Nguyễn Quế Hào",
    "Nguyễn Thị Hồng Phượng",
    "Lê Minh Mẫn",
    "Nguyễn Trọng Trí",
    "Mai Văn Trí",
    "Nguyễn Minh Trí",
    "Nguyễn Thành Tài",
    "Nguyễn Thị Diệu Phước",
    "Lê Anh Vũ",
    "Huỳnh Hữu Phi"
];
export const YEARS = Array.from({ length: 11 }, (_, i) => 2020 + i);
